cms: Headless Commerce {
  shape: image
  icon: https://icons.terrastruct.com/tech/022-server.svg
}

Astro: "Storefront" {
  shape: image
  icon: https://astro.build/assets/press/logomark-light.png
}

cms -> astro: {
  style.animated: true
  style.stroke: 'black'
}

